services:
    postgres:
        image: postgres:latest
        container_name: postgres_db1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: auth_project_test_db
        ports:
            - "5432:5432"
        restart: unless-stopped
